# Generated by Django 4.0.6 on 2022-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='echo',
            name='echo_status',
            field=models.BooleanField(default=False),
        ),
    ]
