# Generated by Django 4.0.6 on 2022-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard', '0002_ad_upload_echo_echo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='upload',
            field=models.FileField(null=True, upload_to='media/uploads/', verbose_name='Загрузить файл'),
        ),
    ]
