# Generated by Django 4.0.6 on 2022-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard', '0006_remove_echo_echo_status_alter_echo_echo_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='echo_status',
            field=models.BooleanField(default=False),
        ),
    ]
